# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='address_two',
            field=models.CharField(blank=True, default=' ', max_length=30, null=True, verbose_name='Address Line 2'),
        ),
    ]
