# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-27 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executiveSummary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesalesexecutive',
            name='region',
            field=models.CharField(choices=[('North', 'North'), ('Central', 'Central'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=7),
        ),
    ]
