# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-23 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('databaseAnalysis', '0003_auto_20171220_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('service_date', models.DateField()),
                ('last_service_miles', models.IntegerField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseAnalysis.Customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseAnalysis.Vehicle')),
            ],
            options={
                'ordering': ['-service_date', 'owner'],
                'verbose_name': 'Customer Service History',
                'verbose_name_plural': 'Customer Service Histories',
            },
        ),
    ]
