# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseAnalysis', '0003_auto_20171220_1901'),
        ('serviceAnalysis', '0003_repairorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('region', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('Central', 'Central'), ('East', 'East'), ('West', 'West')], max_length=7)),
                ('item', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseAnalysis.Dealer')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseAnalysis.Dealership')),
            ],
            options={
                'ordering': ['-date', 'item', 'region'],
                'verbose_name': 'Order History',
                'verbose_name_plural': 'Order Histories',
            },
        ),
    ]
